version: "3.6"
services:
  intercamb-website:
    << : *common
    image: "intercamb-website:latest"
    container_name: "intercamb-website"
    hostname: "intercamb-website"
    volumes:
      - "${INTERCAMB_HOME}/configs/intercamb-website.yml:/usr/src/intercamb-website/server/config.yml"
    networks:
      default:
        ipv4_address: "172.30.5.2"