version: "3.6"
services:
  intercamb:
    << : *common
    image: "intercamb:latest"
    container_name: "intercamb"
    hostname: "intercamb"
    volumes:
      - "${INTERCAMB_HOME}/configs/intercamb.yml:/usr/src/intercamb/config.yml"
      - "${INTERCAMB_HOME}/public:/usr/src/intercamb/public"
    networks:
      default:
        ipv4_address: "172.30.5.1"