version: "3.6"
services:
  nginx:
    << : *common
    image: "nginx:1.15.2-alpine"
    container_name: "nginx"
    hostname: "intercamb-nginx"
    restart: "always"
    volumes:
      - "${INTERCAMB_HOME}/apps/intercamb-configs/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${INTERCAMB_HOME}/data/letsencrypt:/data/letsencrypt"
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        ipv4_address: "172.30.5.10"