version: "3.6"
services:
  mongo:
    << : *common
    image: "mongo:4.1.1"
    container_name: "mongo"
    hostname: "intercamb-mongo"
    restart: "always"
    volumes:
      - "${INTERCAMB_HOME}/apps/intercamb-configs/docker/mongo/default.conf:/usr/local/etc/mongo/mongod.conf"
      - "${INTERCAMB_HOME}/data/mongo:/data/db"
    command: "mongod --config /usr/local/etc/mongo/mongod.conf"
    networks:
      default:
        ipv4_address: "172.30.5.11"
