version: "3.6"
services:
  intercamb-prerender:
    << : *common
    image: "intercamb-prerender:latest"
    container_name: "intercamb-prerender"
    hostname: "intercamb-prerender"
    volumes:
      - "${INTERCAMB_HOME}/configs/intercamb-prerender.yml:/usr/src/intercamb-prerender/config.yml"
    networks:
      default:
        ipv4_address: "172.30.5.3"